#!/bin/bash
./src/misc/informa-users/index.js americanmachinist
./src/misc/informa-users/index.js asumag
./src/misc/informa-users/index.js bulktransporter
./src/misc/informa-users/index.js contractingbusiness
./src/misc/informa-users/index.js contractormag
./src/misc/informa-users/index.js ecmweb
./src/misc/informa-users/index.js ehstoday
./src/misc/informa-users/index.js electricalmarketing
./src/misc/informa-users/index.js electronicdesign
./src/misc/informa-users/index.js ewweb
./src/misc/informa-users/index.js fleetowner
./src/misc/informa-users/index.js forgingmagazine
./src/misc/informa-users/index.js foundrymag
./src/misc/informa-users/index.js hpac
./src/misc/informa-users/index.js hydraulicspneumatics
./src/misc/informa-users/index.js industryweek
./src/misc/informa-users/index.js machinedesign
./src/misc/informa-users/index.js mhlnews
./src/misc/informa-users/index.js mwrf
./src/misc/informa-users/index.js newequipment
./src/misc/informa-users/index.js powerelectronics
./src/misc/informa-users/index.js refrigeratedtransporter
./src/misc/informa-users/index.js rermag
./src/misc/informa-users/index.js sourcetoday
./src/misc/informa-users/index.js tdworld
./src/misc/informa-users/index.js trailerbodybuilders
./src/misc/informa-users/index.js trucker
./src/misc/informa-users/index.js truckfleetmro
